//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sqlite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamInfo
    {
        public int Id { get; set; }
        public string TeamName { get; set; }
        public string JerseyColor { get; set; }
        public string ShortsColor { get; set; }
        public int LeagueTitles { get; set; }
        public int CupTitles { get; set; }
        public decimal KitsPrice { get; set; }
        public decimal BootsPrice { get; set; }
    }
}
